name: General Issue
description: Report a bug, request a feature, or provide feedback.
title: "[ISSUE]: "
labels:
  - needs-triage
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the issue or feature request.
      placeholder: Write the details here...

  - type: markdown
    attributes:
      value: |
        **Steps to Reproduce:**  
        *(If not applicable, write "N/A.")*
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: Example:  
      1. Open the app  
      2. Click on 'Submit'  
      3. Observe the error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Write expected behavior here...

  - type: textarea
    id: screenshots_logs
    attributes:
      label: Screenshots/Logs
      description: Attach screenshots or logs to better explain the issue.
      placeholder: Upload screenshots or paste logs here...

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution (Optional)
      description: Suggest any fixes or ideas for improvement.
      placeholder: Write your solution idea here...

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Provide any extra context, links, or resources.
      placeholder: Add additional context here...
